### ISSUE TITLE
can't access web page at onlyoffice-community-server 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-onlyoffice#12]

**Comment by natk9** [comment]
容器状态、日志正常，服务都启动了，但是9002端口无法进入
![image](https://user-images.githubusercontent.com/40535348/131810017-0043b470-4a10-40cb-9fdd-e4a527a4fe84.png)

**Comment by qiaofeng1227** [comment]
db配置文件不对
