### ISSUE TITLE
Install onlyoffice on AWS linux2 error?

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/ansible-onlyoffice#5]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [x] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
![image](https://user-images.githubusercontent.com/63622990/116510752-fc681480-a8f7-11eb-8145-64837a13791d.png)

# service status 
![image](https://user-images.githubusercontent.com/63622990/116511190-a47ddd80-a8f8-11eb-977f-7d0360047610.png)

# error logs
journalctl -u init-apps
ERROR: for onlyoffice-community-server  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**
When I check system memory:
![image](https://user-images.githubusercontent.com/63622990/116511333-e0b13e00-a8f8-11eb-8cbc-282211d9c513.png)
1.  I think the memory is too low.
2.  compose problems: please show this issues  `https://github.com/docker/compose/issues/3927`
The default request time is 60s:
update this env:
export COMPOSE_HTTP_TIMEOUT=500
export DOCKER_CLIENT_TIMEOUT=500
docker-compose cli env:
https://docs.docker.com/compose/reference/envvars/

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
docker logs onlyoffice

```
         Starting ONLYOFFICE MailAggregator Service...
[  OK  ] Started FastCGI Mono server.
[  OK  ] Started FastCGI Mono server.
[  OK  ] Started Start ONLYOFFICE StorageMigrate Service.
[  OK  ] Started ONLYOFFICE MailWatchdog Service.
[  OK  ] Started ONLYOFFICE Radicale Service.
[  OK  ] Started ONLYOFFICE SocketIO Service.
[  OK  ] Started ONLYOFFICE Feed Service.
[  OK  ] Started ONLYOFFICE MailCleaner Service.
[  OK  ] Started ONLYOFFICE Notify Service.
[  OK  ] Started Start ONLYOFFICE StorageEncryption Service.
[  OK  ] Started Start ONLYOFFICE Backup Service.
[  OK  ] Started System Logging Service.
[  OK  ] Started ONLYOFFICE MailAggregator Service.
[  OK  ] Started God Service.
         Stopping FastCGI Mono server...
         Stopping ONLYOFFICE MailAggregator Service...
         Stopping FastCGI Mono server...
[  OK  ] Stopped FastCGI Mono server.
         Starting FastCGI Mono server...
[  OK  ] Stopped FastCGI Mono server.
[  OK  ] Stopped ONLYOFFICE MailAggregator Service.
         Starting ONLYOFFICE MailAggregator Service...
         Starting FastCGI Mono server...
[  OK  ] Started FastCGI Mono server.
[  OK  ] Started FastCGI Mono server.
[  OK  ] Started ONLYOFFICE MailAggregator Service.
[FAILED] Failed to start Elasticsearch.
See 'systemctl status elasticsearch.service' for details.
         Starting Start ONLYOFFICE Index Service...
         Stopping FastCGI Mono server...
         Stopping FastCGI Mono server...
[  OK  ] Stopped FastCGI Mono server.
[  OK  ] Stopped FastCGI Mono server.
         Starting FastCGI Mono server...
         Starting FastCGI Mono server...
[  OK  ] Started Start ONLYOFFICE Index Service.
[  OK  ] Started FastCGI Mono server.
[  OK  ] Started FastCGI Mono server.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.

```

**Comment by qiaofeng1227** [comment]
Done
