### ISSUE TITLE
自动安装报错

### ISSUE THREAD

**Issue by duronxx** [Websoft9/ansible-onlyoffice#9]
Resolving deltas: 100% (577/577), done.
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
- extracting role_common to /tmp/ansible-onlyoffice/roles/role_common
- role_common was installed successfully
[WARNING]: - role_cloud was NOT installed successfully: - command /bin/git clone http://github.com/websoft9/role_cloud role_cloud failed in directory /root/.ansible/tmp/ansible-local-
144667XkGk2q/tmps4BzEJ (rc=128) - fatal: unable to access 'http://github.com/websoft9/role_cloud/': Encountered end of file
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ERROR! the role 'role_cloud' was not found in /tmp/ansible-onlyoffice/roles:/tmp/ansible-onlyoffice/roles:/tmp/ansible-onlyoffice

The error appears to be in '/tmp/ansible-onlyoffice/onlyoffice.yml': line 31, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
      ^ here
Failed to parse time specification: System will restart in 3s, then installation completed
这个是那出问题了啊，百度也没找到原因，谢谢

**Comment by qiaofeng1227** [comment]
请您确认您的/tmp/ansible-onlyoffice/roles/下是否有role_cloud, 里面是否有内容

**Comment by qiaofeng1227** [comment]
请问您是用如下自动安装脚本运行吗？
```
wget -N https://raw.githubusercontent.com/Websoft9/ansible-linux/main/scripts/install.sh; bash install.sh -r onlyoffice

```
